name: Main

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Needed for "git describe"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "stable"

    - name: Build
      run: make release

    - name: Upload files to a GitHub release
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VER=$(git describe --tags --abbrev=0)
        gh release create --verify-tag --generate-notes $VER ./dist/*
    
