name: Main

on:
  push:
    branches:
    - master
    - develop
    tags:
    - '*'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "stable"

    - name: Build
      run: make release

    - name: Upload files to a GitHub release
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create -d ${{ github.ref }} ./dist/*
    
